version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway_image
    container_name: shareit-gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit-server_image
    container_name: shareit-server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareIt
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:15.1-alpine
    container_name: shareit-db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root